// Code generated by pzero. DO NOT EDIT.
package plugins

import (
	"google.golang.org/grpc"

	"simplerpc-with-model-redis/internal/svc"
)

func LoadPlugins(grpcServer *grpc.Server, svcCtx *svc.ServiceContext) {}
