// Code generated by pzero. DO NOT EDIT.

package model

import (
	"github.com/eddieowens/opts"
	"github.com/polpo666/pzero/core/stores/modelx"
	"github.com/zeromicro/go-zero/core/stores/sqlx"

	"simpleapi-with-model-redis/internal/model/user"
)

type Model struct {
	User user.UserModel
}

func NewModel(conn sqlx.SqlConn, op ...opts.Opt[modelx.ModelOpts]) Model {

	return Model{
		User: user.NewUserModel(conn, op...),
	}
}
