// Code generated by pzero. DO NOT EDIT.
package version

type VersionRequest struct {
}

type VersionResponse struct {
	Version   string `json:"version"`
	GoVersion string `json:"goVersion"`
	Commit    string `json:"commit"`
	Date      string `json:"date"`
}
